# Generated by Django 4.1 on 2022-08-19 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_num',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_bool',
        ),
    ]
