# Generated by Django 4.0.4 on 2023-01-07 02:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_followings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='followings',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
