# Generated by Django 3.0 on 2022-08-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_phone_num_customuser_user_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
