# Generated by Django 4.1 on 2022-08-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_phone_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_bool',
        ),
    ]
