# Generated by Django 4.1 on 2022-08-17 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('origin', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('FLOWER', '꽃'), ('FOLIAGE', '관엽/공기정화'), ('SUCCULENCE', '다육식물'), ('WILD', '야생화/분재'), ('ORCHID', '동/서양란'), ('SEED', '묘묙/씨앗'), ('ELSE', '기타')], max_length=50)),
                ('plant_width', models.FloatField()),
                ('plant_vertical', models.FloatField()),
                ('plant_height', models.FloatField()),
                ('pot_type', models.CharField(max_length=100)),
                ('deliver_type', models.CharField(max_length=50)),
                ('plant_detail', models.TextField()),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('img_number', models.IntegerField()),
                ('is_rep', models.BooleanField()),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.plant')),
            ],
        ),
    ]
