# Generated by Django 4.0.6 on 2022-09-24 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_title', models.CharField(default='꽃 구경하세요:)', max_length=50)),
                ('plant_type', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('view_cnt', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.CharField(choices=[('flower', '꽃'), ('foliage', '관엽/공기정화'), ('succulence', '다육식물'), ('wild', '야생화/분재'), ('orchid', '동/서양란'), ('seed', '묘묙/씨앗'), ('else', '기타')], max_length=50)),
                ('stock', models.IntegerField(default=0)),
                ('origin', models.CharField(choices=[('domestic', '국내산'), ('import', '수입산'), ('else', '모름')], max_length=50)),
                ('plant_width', models.FloatField(blank=True, null=True)),
                ('plant_vertical', models.FloatField(blank=True, null=True)),
                ('plant_height', models.FloatField(blank=True, null=True)),
                ('pot_type', models.CharField(blank=True, max_length=100, null=True)),
                ('deliver_type', models.CharField(choices=[('courier', '택배'), ('direct', '직거래'), ('both', '상관 없음')], max_length=50)),
                ('plant_detail', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
                ('practice', models.TextField()),
                ('plant', models.ManyToManyField(related_name='tagging', to='shop.plant')),
            ],
        ),
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('image_number', models.IntegerField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.plant')),
            ],
        ),
    ]
