# Generated by Django 4.1 on 2022-08-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_plant_pic1_plant_pic10_plant_pic2_plant_pic3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='deliver_type',
            field=models.CharField(choices=[('COURIER', '택배'), ('DIRECT', '직거래'), ('BOTH', '상관 없음')], max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='origin',
            field=models.CharField(choices=[('DOMESTIC', '국내산'), ('IMPORT', '수입산'), ('ELSE', '모름')], max_length=50),
        ),
    ]
