# Generated by Django 4.0.6 on 2022-08-18 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_plant_pub_date_alter_plant_deliver_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='pic1',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='pic10',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='pic2',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='pic3',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='pic4',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='pic5',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='pic6',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='pic7',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='pic8',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='pic9',
        ),
        migrations.AddField(
            model_name='plant',
            name='feed_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='view_cnt',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('img_number', models.IntegerField()),
                ('is_rep', models.BooleanField(blank=True)),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.plant')),
            ],
        ),
    ]
