# Generated by Django 4.0.6 on 2022-08-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_tag'),
        ('shop', '0005_rename_img_number_plantimage_image_number'),
    ]

    operations = [
    ]
