# Generated by Django 4.0.6 on 2022-09-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_tag_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='plant',
        ),
        migrations.AddField(
            model_name='plant',
            name='tags',
            field=models.ManyToManyField(blank=True, to='shop.tag'),
        ),
    ]
