# Generated by Django 4.0.6 on 2022-08-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_merge_20220818_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='plant_name',
            new_name='plant_type',
        ),
        migrations.AlterField(
            model_name='plant',
            name='feed_title',
            field=models.CharField(default='꽃 구경하세요:)', max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plant',
            name='view_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
