# Generated by Django 4.0.6 on 2022-08-18 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_plant_name_plant_plant_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantimage',
            old_name='plant_id',
            new_name='plant',
        ),
    ]
