# Generated by Django 4.0.6 on 2022-08-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_plant_id_plantimage_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantimage',
            name='is_rep',
        ),
    ]
