# Generated by Django 4.0.6 on 2022-09-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_tag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='shop.tag'),
        ),
    ]
