# Generated by Django 4.1 on 2022-08-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_planttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('flower', '꽃'), ('foliage', '관엽/공기정화'), ('succulence', '다육식물'), ('wild', '야생화/분재'), ('orchid', '동/서양란'), ('seed', '묘묙/씨앗'), ('else', '기타')], max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='deliver_type',
            field=models.CharField(choices=[('courier', '택배'), ('direct', '직거래'), ('both', '상관 없음')], max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='origin',
            field=models.CharField(choices=[('domestic', '국내산'), ('import', '수입산'), ('else', '모름')], max_length=50),
        ),
    ]
