# Generated by Django 3.0 on 2022-08-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_tag_plant_id_plant_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('flower', '꽃'), ('foliage', '관엽/공기정화'), ('succulence', '다육식물'), ('wild', '야생화/분재'), ('orchid', '동/서양란'), ('seed', '묘묙/씨앗'), ('else', '기타')], max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='deliver_type',
            field=models.CharField(choices=[('courier', '택배'), ('direct', '직거래'), ('both', '상관 없음')], max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='origin',
            field=models.CharField(choices=[('domestic', '국내산'), ('import', '수입산'), ('else', '모름')], max_length=50),
        ),
        migrations.AlterField(
            model_name='plantimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='planttype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
