# Generated by Django 4.1 on 2022-08-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_plant_category_alter_plant_deliver_type_and_more'),
        ('shop', '0011_remove_tag_plant_id_plant_tags'),
    ]

    operations = [
    ]
