# Generated by Django 4.0.6 on 2022-09-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_tag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='img_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantimage',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
