# Generated by Django 3.0 on 2022-08-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_merge_20220819_2135'),
        ('shop', '0012_auto_20220819_1257'),
    ]

    operations = [
    ]
