# Generated by Django 4.1 on 2022-09-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_plant_category_alter_plant_deliver_type_and_more'),
        ('shop', '0012_auto_20220819_1257'),
        ('shop', '0012_merge_20220819_2135'),
    ]

    operations = [
    ]
