# Generated by Django 4.1.3 on 2023-01-08 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_plant_img_url_alter_plantimage_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='plant_tags',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
