# Generated by Django 4.1.3 on 2023-01-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('shop', '0013_remove_plant_plant_tags_remove_plant_tags_delete_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlantType',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='plant_type',
        ),
        migrations.RemoveField(
            model_name='plantimage',
            name='image_number',
        ),
        migrations.RemoveField(
            model_name='plantimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_name',
            field=models.CharField(default='식물', max_length=50),
        ),
        migrations.AddField(
            model_name='plant',
            name='shop_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='tagDB',
            field=models.ManyToManyField(related_name='shop_tags', to='home.tag'),
        ),
        migrations.AddField(
            model_name='plantimage',
            name='image',
            field=models.TextField(default='img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plant',
            name='img_url',
            field=models.TextField(blank=True, default='default_img', null=True),
        ),
    ]
