# Generated by Django 4.1.3 on 2023-01-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_delete_planttype_remove_plant_plant_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
