# Generated by Django 4.1.3 on 2023-01-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_plant_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
