# Generated by Django 4.1.3 on 2023-01-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_plant_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='img_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
