# Generated by Django 4.1.3 on 2022-12-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_img', models.TextField(blank=True, null=True)),
                ('like', models.IntegerField(default=0)),
                ('view_cnt', models.IntegerField(default=0)),
                ('order', models.CharField(choices=[('latest', '최신순'), ('count', '조회순'), ('like', '좋아요순'), ('comment', '댓글순')], max_length=50)),
                ('category', models.CharField(choices=[('flower', '꽃'), ('foliage', '관엽/공기정화'), ('succulence', '다육식물'), ('wild', '야생화/분재'), ('orchid', '동/서양란'), ('seed', '묘묙/씨앗'), ('else', '기타')], max_length=50)),
                ('place', models.CharField(choices=[('inside', '실내'), ('outside', '야외')], max_length=50)),
                ('plant_tags', models.TextField(blank=True, null=True)),
                ('img_url', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('book_mark', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Community',
        ),
    ]
