# Generated by Django 4.1.3 on 2023-01-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_plantdiary_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='QnA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='질문', max_length=200)),
                ('body', models.TextField(blank=True, null=True)),
                ('img_url', models.TextField(blank=True, null=True)),
                ('qna_tag', models.TextField(blank=True, null=True)),
                ('view_cnt', models.IntegerField(default=0)),
            ],
        ),
    ]
