# Generated by Django 4.1.3 on 2023-01-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_rename_qna_tag_qna_qna_tags_qnaimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='img_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qna',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
