# Generated by Django 4.1.3 on 2023-02-04 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_remove_plantdiary_book_mark_remove_plantdiary_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantdiary',
            name='username',
        ),
    ]
