# Generated by Django 4.1.3 on 2023-02-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_plantdiary_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdiary',
            name='place',
            field=models.CharField(choices=[('indoor', '실내'), ('outdoor', '야외')], max_length=50),
        ),
    ]
