# Generated by Django 4.1.3 on 2023-02-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_alter_plantdiary_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdiary',
            name='category',
            field=models.CharField(blank=True, choices=[('flower', '꽃'), ('foliage', '관엽/공기정화'), ('succulence', '다육식물'), ('wild', '야생화/분재'), ('orchid', '동/서양란'), ('seed', '묘묙/씨앗'), ('else', '기타')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plantdiary',
            name='place',
            field=models.CharField(blank=True, choices=[('indoor', '실내'), ('outdoor', '야외')], max_length=50, null=True),
        ),
    ]
