# Generated by Django 4.1.3 on 2023-02-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_alter_plantdiary_plantprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdiary',
            name='plantprofile',
            field=models.CharField(blank=True, default='선택 안 함', max_length=50, null=True),
        ),
    ]
