# Generated by Django 4.1.3 on 2023-02-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_alter_plantdiary_plantprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdiary',
            name='plantprofile',
            field=models.CharField(default='미정', max_length=50),
        ),
    ]
